- id: gitlater
  name: gitlater (legacy)
  entry: gitlater check
  language: python
  pass_filenames: false

- id: gitlater-check
  name: gitlater (check)
  entry: gitlater check
  language: python
  pass_filenames: false
